#!/bin/sh

set -ex

gitpath=$1
case "$gitpath" in
	/*)
		;;
	*)
		gitpath="`pwd`/$gitpath"
		;;
esac

(
	cd "$gitpath"
	git --bare svn fetch
	git --bare fetch
	git --bare update-server-info
	git --bare push mirror --all || true
	git --bare push mirror --tags || true
)
