#!/bin/sh

git log --format=raw | while IFS= read -r L; do
	case "$L" in
		'    Merge branches '*|'    Merge remote branches '*)
			b=`echo "$L" | sed -e "s/[^']*'\?\([^']*\)'\?/\1 /g"`
			git merge $b
			break
			;;
	esac
done
