#!/bin/sh

set -ex

gitpath=$1
case "$gitpath" in
	/*)
		;;
	*)
		gitpath="`pwd`/$gitpath"
		;;
esac

(
	cd "$gitpath"
	git --bare svn fetch
	git --bare fetch
	git --bare update-server-info
	[ -x hooks/post-update ] && hooks/post-update
)
